In [29]:
import brt
import torch.nn as nn
import torch

@brt.top_graph
class SimpleNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear1 = nn.Linear(10, 10)
        self.linear2 = nn.Linear(10, 10)

    def forward(self, x):
        x = self.linear1(x)
        x = self.linear2(x)
        return x

simple_net = SimpleNet()

x = torch.Tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
x = simple_net(x)
print(x)
script_simple_net = torch.jit.script(simple_net)
simple_net_inlined_graph = script_simple_net.inlined_graph
print(simple_net_inlined_graph)

unwrap_redundant_netlet due to top_graph
unwrap_redundant_netlet due to no router
unwrap_redundant_netlet due to no router
unwrap_redundant_netlet due to no router
tensor([-1.8560, -1.4745, -2.0467, -0.9605, -0.9353,  1.0686, -2.4302,  0.2452,
         0.0262, -0.3079], grad_fn=<AddBackward0>)
graph(%self : __torch__.brt.primitive.___torch_mangle_18.wrapper,
      %x.1 : Tensor):
  %linear1 : __torch__.torch.nn.modules.linear.Linear = prim::GetAttr[name="linear1"](%self)
  %6 : Function = prim::Constant[name="linear"]()
  %weight.1 : Tensor = prim::GetAttr[name="weight"](%linear1)
  %bias.1 : Tensor = prim::GetAttr[name="bias"](%linear1)
  %x.5 : Tensor = aten::linear(%x.1, %weight.1, %bias.1) # /state/partition/whcui/tools/pyenv/versions/miniconda3-4.7.12/lib/python3.7/site-packages/torch/nn/functional.py:1848:11
  %linear2 : __torch__.torch.nn.modules.linear.Linear = prim::GetAttr[name="linear2"](%self)
  %10 : Function = prim::Constant[name="linear"]()
  %weight : Tensor = prim::Get

In [30]:
from nni.retiarii.converter import convert_to_graph
from nni.retiarii.codegen import model_to_pytorch_script
model_ir = convert_to_graph(script_simple_net, simple_net)

for node in model_ir.get_nodes():
    print(node)

print("-----------------")

for cell_node in model_ir.get_cell_nodes():
    print(cell_node)

model_code = model_to_pytorch_script(model_ir)
print(model_code)

ValueError: Object Linear(in_features=10, out_features=10, bias=True) needs to be serializable but `trace_kwargs` is not available. If it is a built-in module (like Conv2d), please import it from retiarii.nn. If it is a customized module, please to decorate it with @basic_unit. For other complex objects (e.g., trainer, optimizer, dataset, dataloader), try to use @nni.trace.

In [6]:
import torch
import brt
import brt.nn as nn
from brt.router import RandomScatterRouter, RandomGatherRouter


class MoE(nn.Module):
    def __init__(self):
        super().__init__()
        self.scatter_router = RandomScatterRouter(route_num=2)
        self.expert1 = nn.Linear(10, 10)
        self.expert2 = nn.Linear(10, 10)
        self.gather_router = RandomGatherRouter(route_num=2)

    def forward(self, x):
        route_results, reverse_indice, origin_shape = self.scatter_router(x)
        x_0 = self.expert1(route_results[0])
        x_1 = self.expert2(route_results[1])
        x = self.gather_router(
            reverse_indice,
            origin_shape,
            x_0,
            x_1,
        )
        return x


@brt.top_graph
@brt.netlet
class MoEModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.moe = MoE()

    def forward(self, x):
        return self.moe(x)


moe_model = MoEModel()

x = torch.Tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])
# model.cuda()
y = 10
z = moe_model(x)
print(z)


# model.brt_script(True)
script_moe_model = torch.jit.script(moe_model)
print(script_moe_model.inlined_graph)


unwrap_redundant_netlet due to top_graph
unwrap_redundant_netlet due to no router
unwrap_redundant_netlet due to no router
unwrap_redundant_netlet due to no router
unwrap_redundant_netlet due to no router
unwrap_redundant_netlet due to no router
using brt_forward
using brt_forward
tensor([[ 8.0769,  1.7423, -7.9711, -0.3013,  3.9045, -1.5637,  6.9472, -0.1561,
         -6.9773,  2.2685],
        [ 8.0769,  1.7423, -7.9711, -0.3013,  3.9045, -1.5637,  6.9472, -0.1561,
         -6.9773,  2.2685]], grad_fn=<ViewBackward0>)
graph(%self : __torch__.brt.primitive.___torch_mangle_8.wrapper,
      %x.1 : Tensor):
  %moe : __torch__.___torch_mangle_7.MoE = prim::GetAttr[name="moe"](%self)
  %4 : Function = prim::Constant[name="linear"]()
  %5 : int = prim::Constant[value=1]() # /tmp/ipykernel_1894377/268797626.py:18:41
  %6 : int = prim::Constant[value=0]() # /tmp/ipykernel_1894377/268797626.py:17:41
  %scatter_router : __torch__.brt.router.scatter_router.RandomScatterRouter = prim::GetAttr[nam

In [11]:
from nni.retiarii.converter import convert_to_graph
from nni.retiarii.codegen import model_to_pytorch_script
model_ir = convert_to_graph(script_moe_model, moe_model)

for node in model_ir.get_nodes():
    print(node)

print("-----------------")

for cell_node in model_ir.get_cell_nodes():
    print(cell_node)

model_code = model_to_pytorch_script(model_ir)


Node(id=-1, name=_inputs, python_name=None, label=None, operation=_IOPseudoOperation(type="_inputs"))
Node(id=-2, name=_outputs, python_name=None, label=None, operation=_IOPseudoOperation(type="_outputs"))
Node(id=114, name=_model__moe__expert1__Attr10, python_name=None, label=None, operation=PrimGetAttr(type="prim::GetAttr", name='weight', input='self', value=None))
Node(id=115, name=_model__moe__expert1__Attr11, python_name=None, label=None, operation=PrimGetAttr(type="prim::GetAttr", name='bias', input='self', value=None))
Node(id=116, name=_model__moe__expert1__linear12, python_name=moe.expert1.linear, label=None, operation=FunctionalOperator(type="Function.linear"))
Node(id=-1, name=_inputs, python_name=None, label=None, operation=_IOPseudoOperation(type="_inputs"))
Node(id=-2, name=_outputs, python_name=None, label=None, operation=_IOPseudoOperation(type="_outputs"))
Node(id=121, name=_model__moe__expert2__Attr16, python_name=None, label=None, operation=PrimGetAttr(type="prim::Ge

RuntimeError: unsupported operation type: prim::PythonOp ? None

In [ ]:
import torch
import torch.nn as nn


class MyModule(nn.Module):
    def __init__(self, use_memory_efficient):
        super(MyModule, self).__init__()
        self.use_memory_efficient = use_memory_efficient

    @torch.jit.ignore(drop=True)
    def memory_efficient(self, x):
        import pdb

        pdb.set_trace()
        return x + 10

    def forward(self, x):
        # Use not-yet-scriptable memory efficient mode
        if self.use_memory_efficient:
            return self.memory_efficient(x)
        else:
            return x + 10


m = torch.jit.script(MyModule(use_memory_efficient=False))
# m.save("m.pt")

m = torch.jit.script(MyModule(use_memory_efficient=True))
# exception raised
print(m.inlined_graph)
# m.save("m.pt")
# m(torch.rand(100))


In [1]:
import brt.nn as nn
import torch
from brt import netlet, top_graph
from brt.primitive import unwrap_netlet, unwrap_redundant_netlet

@top_graph
@netlet
class RedundantModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(10, 10)

    def forward(self, x):
        return self.linear(x)


redundant_model = RedundantModel()
x = torch.Tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x = redundant_model(x)
print(x)

# assert redundant_model._netlet_tag == True, "netlet_tag is not set"
# assert redundant_model._top_graph == True, "top_graph is not set"

redundant_model = unwrap_redundant_netlet(redundant_model)

x = redundant_model(x)

print(x)


tensor([-1.6597,  1.9257, -1.5097, -4.6707, -0.4496,  3.1321,  1.4132,  1.1851,
         0.9164,  0.7567], grad_fn=<AddBackward0>)
tensor([-1.3143, -1.6946, -0.8486,  0.4667,  0.3905, -0.5602,  0.1592, -0.5632,
         1.1540, -1.0938], grad_fn=<AddBackward0>)


In [20]:
import os
import sys
import unittest
from typing import (Dict)

import numpy as np
import torch
import torch.nn.functional as F
import torchvision

import nni.retiarii.nn.pytorch as nn
from nni.retiarii.codegen import model_to_pytorch_script
from nni.retiarii.utils import original_state_dict_hooks
from nni.retiarii.converter.graph_gen import convert_to_graph, GraphConverterWithShape

class ConvertMixin:
    @staticmethod
    def _convert_model(model, input):
        script_module = torch.jit.script(model)
        model_ir = convert_to_graph(script_module, model)
        return model_ir

class TestModels(unittest.TestCase,ConvertMixin):

    def run_test(self, model, input, check_value=True):
        model_ir = self._convert_model(model, input)
        model_code = model_to_pytorch_script(model_ir)
        print(model_code)

        exec_vars = {}
        exec(model_code + '\n\nconverted_model = _model()', exec_vars)
        converted_model = exec_vars['converted_model']

        with original_state_dict_hooks(converted_model):
            converted_model.load_state_dict(model.state_dict())

        with torch.no_grad():
            expected_output = model.eval()(*input)
            converted_output = converted_model.eval()(*input)
        if check_value:
            try:
                self.assertEqual(len(converted_output), len(expected_output))
                for a, b in zip(converted_output, expected_output):
                    torch.eq(a, b)
            except:
                self.assertEqual(converted_output, expected_output)
        return converted_model

    def test_nested_modulelist(self):
        class Net(nn.Module):
            def __init__(self, num_nodes, num_ops_per_node):
                super().__init__()
                self.ops = nn.ModuleList()
                self.num_nodes = num_nodes
                self.num_ops_per_node = num_ops_per_node
                for _ in range(num_nodes):
                    self.ops.append(nn.ModuleList([nn.Linear(16, 16) for __ in range(num_ops_per_node)]))

            def forward(self, x):
                state = x
                for ops in self.ops:
                    for op in ops:
                        state = op(state)
                return state

        model = Net(4, 2)
        x = torch.rand((16, 16), dtype=torch.float)
        self.run_test(model, (x, ))

    def test_append_input_tensor(self):
        from typing import List

        class Net(nn.Module):
            def __init__(self, num_nodes):
                super().__init__()
                self.ops = nn.ModuleList()
                self.num_nodes = num_nodes
                for _ in range(num_nodes):
                    self.ops.append(nn.Linear(16, 16))

            def forward(self, x: List[torch.Tensor]):
                state = x
                for ops in self.ops:
                    state.append(ops(state[-1]))
                return state[-1]

        model = Net(4)
        x = torch.rand((1, 16), dtype=torch.float)
        self.run_test(model, ([x], ))

    def test_channels_shuffle(self):
        class Net(nn.Module):
            def forward(self, x):
                bs, num_channels, height, width = x.size()
                x = x.reshape(bs * num_channels // 2, 2, height * width)
                x = x.permute(1, 0, 2)
                x = x.reshape(2, -1, num_channels // 2, height, width)
                return x[0], x[1]

        model = Net()
        x = torch.rand((1, 64, 224, 224), dtype=torch.float)
        self.run_test(model, (x, ))

    def test_identity_node(self):
        class Net(nn.Module):
            def forward(self, x):
                return x

        model = Net()
        x = torch.rand((1, 64, 224, 224), dtype=torch.float)
        self.run_test(model, (x, ))

    def test_nn_sequential_inherit(self):
        class ConvBNReLU(nn.Sequential):
            def __init__(self):
                super().__init__(
                    nn.Conv2d(3, 3, 1, 1, bias=False),
                    nn.BatchNorm2d(3),
                    nn.ReLU(inplace=False)
                )

        class Net(nn.Module):
            def __init__(self):
                super().__init__()
                self.conv_bn_relu = ConvBNReLU()
                
            def forward(self, x):
                return self.conv_bn_relu(x)

        model = Net()
        x = torch.rand((1, 3, 224, 224), dtype=torch.float)
        self.run_test(model, (x, ))

test_models = TestModels()
test_models.test_nn_sequential_inherit()


import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

import nni.retiarii.nn.pytorch

import torch


class _model__conv_bn_relu(nn.Module):
    def __init__(self):
        super().__init__()
        self._0 = torch.nn.modules.conv.Conv2d(in_channels=3, out_channels=3, kernel_size=1, stride=1, bias=False)
        self._1 = torch.nn.modules.batchnorm.BatchNorm2d(num_features=3)
        self._2 = torch.nn.modules.activation.ReLU(inplace=False)
        self._mapping_ = {'_0': 'conv_bn_relu.0', '_1': 'conv_bn_relu.1', '_2': 'conv_bn_relu.2'}

    def forward(self, input__1):
        _0 = self._0(input__1)
        _1 = self._1(_0)
        _2 = self._2(_1)
        return _2



class _model(nn.Module):
    def __init__(self):
        super().__init__()
        self._conv_bn_relu = _model__conv_bn_relu()
        self._mapping_ = {'_conv_bn_relu': 'conv_bn_relu'}

    def forward(self, x__1):
        _conv_bn_relu = self._conv_bn_relu(x__1)
        retur