In [26]:
from brt._C.router import generate_dst_indices
import torch
hot_mask = torch.randint(0, 2, (16, 4), dtype=torch.int32).cuda()
print(hot_mask)

tensor([[0, 1, 0, 1],
        [0, 0, 1, 1],
        [1, 1, 1, 0],
        [0, 1, 0, 1],
        [1, 0, 1, 1],
        [1, 0, 1, 1],
        [0, 1, 0, 1],
        [0, 0, 0, 1],
        [0, 0, 0, 0],
        [0, 0, 1, 1],
        [1, 0, 0, 1],
        [1, 1, 0, 1],
        [0, 0, 0, 0],
        [0, 1, 1, 0],
        [1, 0, 1, 0],
        [0, 1, 0, 1]], device='cuda:0', dtype=torch.int32)


In [27]:
indices, loads = generate_dst_indices(hot_mask)
# print(indices[0].is_contiguous())
print(indices)


tensor([[ 0,  1,  0,  1],
        [ 0,  0,  1,  2],
        [ 1,  2,  2,  0],
        [ 0,  3,  0,  3],
        [ 2,  0,  3,  4],
        [ 3,  0,  4,  5],
        [ 0,  4,  0,  6],
        [ 0,  0,  0,  7],
        [ 0,  0,  0,  0],
        [ 0,  0,  5,  8],
        [ 4,  0,  0,  9],
        [ 5,  5,  0, 10],
        [ 0,  0,  0,  0],
        [ 0,  6,  6,  0],
        [ 6,  0,  7,  0],
        [ 0,  7,  0, 11]], device='cuda:0', dtype=torch.int32)


In [28]:
placement_indices = torch.index_select(
    indices, 1, torch.tensor([3, 2, 1, 0], dtype=torch.int32).cuda()
)
print(placement_indices)

tensor([[ 1,  0,  1,  0],
        [ 2,  1,  0,  0],
        [ 0,  2,  2,  1],
        [ 3,  0,  3,  0],
        [ 4,  3,  0,  2],
        [ 5,  4,  0,  3],
        [ 6,  0,  4,  0],
        [ 7,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 8,  5,  0,  0],
        [ 9,  0,  0,  4],
        [10,  0,  5,  5],
        [ 0,  0,  0,  0],
        [ 0,  6,  6,  0],
        [ 0,  7,  0,  6],
        [11,  0,  7,  0]], device='cuda:0', dtype=torch.int32)
